### ISSUE TITLE
Field Validation Warning Messages do not Persist

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#77]
Field validation warning messages flagging invalid data do not persist on the following screens: Add/Update Assembly, Part and Location Templates, Add/Update Types, Add/Update Custom Fields, Add/Update Location, Add/Update Inventory, and Add/Update Builds to name a few.

Field validation warning message do persist when adding a Part to a Part Template and when editing a Revision. 

Field validation warning messages that do not persist disappear from the screen after a few seconds. This is problematic for the user and for automating testing.

**Comment by rhmunier** [comment]
Conversely, some of the database validation fields do not remove their warning leaving many instances of the error bar.  Duplicate serial numbers is one example.

**Comment by ethanandrews** [comment]
@joannekoch @rhmunier Both validation message issues raised here have been fixed, up on staging or testing

**Comment by joannekoch** [comment]
Some issues still persist.
1. When add Inventory, no error message for blank Part Type (required field).
2. When create new Build - there is no auto-generated Build Number assigned.

Everything else look fine.

**Comment by joannekoch** [comment]
In addition to previous comment, an empty Part Template field error does not persist when adding a Sub-Assembly part.
